# This is a basic workflow to help you get started with Actions

name: Helm Chart

on:
  push:
    branches:
      - master
    paths:
      - 'chart/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses:  rccrdpccl/helm-push-action@v3
      env:
        SOURCE_DIR: 'chart'
        CHART_FOLDER: 'node-policy-webhook'
        CHARTMUSEUM_URL: 'https://charts.softonic.io'
        CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
        CHARTMUSEUM_PASSWORD: '${{ secrets.CHARTMUSEUM_PASSWORD }}'
